/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.orion.adapter.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ACall extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8939733618337334131L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ACall\",\"namespace\":\"com.orion.adapter.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"callerNumber\",\"type\":\"string\"},{\"name\":\"calledNumber\",\"type\":\"string\"},{\"name\":\"engagementDialogId\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"string\"},{\"name\":\"participant\",\"type\":{\"type\":\"record\",\"name\":\"AParticipant\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ACall> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ACall> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ACall> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ACall> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ACall> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ACall to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ACall from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ACall instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ACall fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence callerNumber;
  private java.lang.CharSequence calledNumber;
  private java.lang.CharSequence engagementDialogId;
  private java.lang.CharSequence timestamp;
  private com.orion.adapter.avro.AParticipant participant;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ACall() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param callerNumber The new value for callerNumber
   * @param calledNumber The new value for calledNumber
   * @param engagementDialogId The new value for engagementDialogId
   * @param timestamp The new value for timestamp
   * @param participant The new value for participant
   */
  public ACall(java.lang.CharSequence id, java.lang.CharSequence callerNumber, java.lang.CharSequence calledNumber, java.lang.CharSequence engagementDialogId, java.lang.CharSequence timestamp, com.orion.adapter.avro.AParticipant participant) {
    this.id = id;
    this.callerNumber = callerNumber;
    this.calledNumber = calledNumber;
    this.engagementDialogId = engagementDialogId;
    this.timestamp = timestamp;
    this.participant = participant;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return callerNumber;
    case 2: return calledNumber;
    case 3: return engagementDialogId;
    case 4: return timestamp;
    case 5: return participant;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: callerNumber = (java.lang.CharSequence)value$; break;
    case 2: calledNumber = (java.lang.CharSequence)value$; break;
    case 3: engagementDialogId = (java.lang.CharSequence)value$; break;
    case 4: timestamp = (java.lang.CharSequence)value$; break;
    case 5: participant = (com.orion.adapter.avro.AParticipant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'callerNumber' field.
   * @return The value of the 'callerNumber' field.
   */
  public java.lang.CharSequence getCallerNumber() {
    return callerNumber;
  }


  /**
   * Sets the value of the 'callerNumber' field.
   * @param value the value to set.
   */
  public void setCallerNumber(java.lang.CharSequence value) {
    this.callerNumber = value;
  }

  /**
   * Gets the value of the 'calledNumber' field.
   * @return The value of the 'calledNumber' field.
   */
  public java.lang.CharSequence getCalledNumber() {
    return calledNumber;
  }


  /**
   * Sets the value of the 'calledNumber' field.
   * @param value the value to set.
   */
  public void setCalledNumber(java.lang.CharSequence value) {
    this.calledNumber = value;
  }

  /**
   * Gets the value of the 'engagementDialogId' field.
   * @return The value of the 'engagementDialogId' field.
   */
  public java.lang.CharSequence getEngagementDialogId() {
    return engagementDialogId;
  }


  /**
   * Sets the value of the 'engagementDialogId' field.
   * @param value the value to set.
   */
  public void setEngagementDialogId(java.lang.CharSequence value) {
    this.engagementDialogId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.CharSequence getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.CharSequence value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'participant' field.
   * @return The value of the 'participant' field.
   */
  public com.orion.adapter.avro.AParticipant getParticipant() {
    return participant;
  }


  /**
   * Sets the value of the 'participant' field.
   * @param value the value to set.
   */
  public void setParticipant(com.orion.adapter.avro.AParticipant value) {
    this.participant = value;
  }

  /**
   * Creates a new ACall RecordBuilder.
   * @return A new ACall RecordBuilder
   */
  public static com.orion.adapter.avro.ACall.Builder newBuilder() {
    return new com.orion.adapter.avro.ACall.Builder();
  }

  /**
   * Creates a new ACall RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ACall RecordBuilder
   */
  public static com.orion.adapter.avro.ACall.Builder newBuilder(com.orion.adapter.avro.ACall.Builder other) {
    if (other == null) {
      return new com.orion.adapter.avro.ACall.Builder();
    } else {
      return new com.orion.adapter.avro.ACall.Builder(other);
    }
  }

  /**
   * Creates a new ACall RecordBuilder by copying an existing ACall instance.
   * @param other The existing instance to copy.
   * @return A new ACall RecordBuilder
   */
  public static com.orion.adapter.avro.ACall.Builder newBuilder(com.orion.adapter.avro.ACall other) {
    if (other == null) {
      return new com.orion.adapter.avro.ACall.Builder();
    } else {
      return new com.orion.adapter.avro.ACall.Builder(other);
    }
  }

  /**
   * RecordBuilder for ACall instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ACall>
    implements org.apache.avro.data.RecordBuilder<ACall> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence callerNumber;
    private java.lang.CharSequence calledNumber;
    private java.lang.CharSequence engagementDialogId;
    private java.lang.CharSequence timestamp;
    private com.orion.adapter.avro.AParticipant participant;
    private com.orion.adapter.avro.AParticipant.Builder participantBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.orion.adapter.avro.ACall.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.callerNumber)) {
        this.callerNumber = data().deepCopy(fields()[1].schema(), other.callerNumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.calledNumber)) {
        this.calledNumber = data().deepCopy(fields()[2].schema(), other.calledNumber);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.engagementDialogId)) {
        this.engagementDialogId = data().deepCopy(fields()[3].schema(), other.engagementDialogId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.participant)) {
        this.participant = data().deepCopy(fields()[5].schema(), other.participant);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (other.hasParticipantBuilder()) {
        this.participantBuilder = com.orion.adapter.avro.AParticipant.newBuilder(other.getParticipantBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ACall instance
     * @param other The existing instance to copy.
     */
    private Builder(com.orion.adapter.avro.ACall other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.callerNumber)) {
        this.callerNumber = data().deepCopy(fields()[1].schema(), other.callerNumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.calledNumber)) {
        this.calledNumber = data().deepCopy(fields()[2].schema(), other.calledNumber);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.engagementDialogId)) {
        this.engagementDialogId = data().deepCopy(fields()[3].schema(), other.engagementDialogId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[4].schema(), other.timestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.participant)) {
        this.participant = data().deepCopy(fields()[5].schema(), other.participant);
        fieldSetFlags()[5] = true;
      }
      this.participantBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'callerNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallerNumber() {
      return callerNumber;
    }


    /**
      * Sets the value of the 'callerNumber' field.
      * @param value The value of 'callerNumber'.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder setCallerNumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.callerNumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'callerNumber' field has been set.
      * @return True if the 'callerNumber' field has been set, false otherwise.
      */
    public boolean hasCallerNumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'callerNumber' field.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder clearCallerNumber() {
      callerNumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'calledNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getCalledNumber() {
      return calledNumber;
    }


    /**
      * Sets the value of the 'calledNumber' field.
      * @param value The value of 'calledNumber'.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder setCalledNumber(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.calledNumber = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'calledNumber' field has been set.
      * @return True if the 'calledNumber' field has been set, false otherwise.
      */
    public boolean hasCalledNumber() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'calledNumber' field.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder clearCalledNumber() {
      calledNumber = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'engagementDialogId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEngagementDialogId() {
      return engagementDialogId;
    }


    /**
      * Sets the value of the 'engagementDialogId' field.
      * @param value The value of 'engagementDialogId'.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder setEngagementDialogId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.engagementDialogId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'engagementDialogId' field has been set.
      * @return True if the 'engagementDialogId' field has been set, false otherwise.
      */
    public boolean hasEngagementDialogId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'engagementDialogId' field.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder clearEngagementDialogId() {
      engagementDialogId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.CharSequence getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder setTimestamp(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.timestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'participant' field.
      * @return The value.
      */
    public com.orion.adapter.avro.AParticipant getParticipant() {
      return participant;
    }


    /**
      * Sets the value of the 'participant' field.
      * @param value The value of 'participant'.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder setParticipant(com.orion.adapter.avro.AParticipant value) {
      validate(fields()[5], value);
      this.participantBuilder = null;
      this.participant = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'participant' field has been set.
      * @return True if the 'participant' field has been set, false otherwise.
      */
    public boolean hasParticipant() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'participant' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.orion.adapter.avro.AParticipant.Builder getParticipantBuilder() {
      if (participantBuilder == null) {
        if (hasParticipant()) {
          setParticipantBuilder(com.orion.adapter.avro.AParticipant.newBuilder(participant));
        } else {
          setParticipantBuilder(com.orion.adapter.avro.AParticipant.newBuilder());
        }
      }
      return participantBuilder;
    }

    /**
     * Sets the Builder instance for the 'participant' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.orion.adapter.avro.ACall.Builder setParticipantBuilder(com.orion.adapter.avro.AParticipant.Builder value) {
      clearParticipant();
      participantBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'participant' field has an active Builder instance
     * @return True if the 'participant' field has an active Builder instance
     */
    public boolean hasParticipantBuilder() {
      return participantBuilder != null;
    }

    /**
      * Clears the value of the 'participant' field.
      * @return This builder.
      */
    public com.orion.adapter.avro.ACall.Builder clearParticipant() {
      participant = null;
      participantBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ACall build() {
      try {
        ACall record = new ACall();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.callerNumber = fieldSetFlags()[1] ? this.callerNumber : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.calledNumber = fieldSetFlags()[2] ? this.calledNumber : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.engagementDialogId = fieldSetFlags()[3] ? this.engagementDialogId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.timestamp = fieldSetFlags()[4] ? this.timestamp : (java.lang.CharSequence) defaultValue(fields()[4]);
        if (participantBuilder != null) {
          try {
            record.participant = this.participantBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("participant"));
            throw e;
          }
        } else {
          record.participant = fieldSetFlags()[5] ? this.participant : (com.orion.adapter.avro.AParticipant) defaultValue(fields()[5]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ACall>
    WRITER$ = (org.apache.avro.io.DatumWriter<ACall>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ACall>
    READER$ = (org.apache.avro.io.DatumReader<ACall>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.callerNumber);

    out.writeString(this.calledNumber);

    out.writeString(this.engagementDialogId);

    out.writeString(this.timestamp);

    this.participant.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.callerNumber = in.readString(this.callerNumber instanceof Utf8 ? (Utf8)this.callerNumber : null);

      this.calledNumber = in.readString(this.calledNumber instanceof Utf8 ? (Utf8)this.calledNumber : null);

      this.engagementDialogId = in.readString(this.engagementDialogId instanceof Utf8 ? (Utf8)this.engagementDialogId : null);

      this.timestamp = in.readString(this.timestamp instanceof Utf8 ? (Utf8)this.timestamp : null);

      if (this.participant == null) {
        this.participant = new com.orion.adapter.avro.AParticipant();
      }
      this.participant.customDecode(in);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.callerNumber = in.readString(this.callerNumber instanceof Utf8 ? (Utf8)this.callerNumber : null);
          break;

        case 2:
          this.calledNumber = in.readString(this.calledNumber instanceof Utf8 ? (Utf8)this.calledNumber : null);
          break;

        case 3:
          this.engagementDialogId = in.readString(this.engagementDialogId instanceof Utf8 ? (Utf8)this.engagementDialogId : null);
          break;

        case 4:
          this.timestamp = in.readString(this.timestamp instanceof Utf8 ? (Utf8)this.timestamp : null);
          break;

        case 5:
          if (this.participant == null) {
            this.participant = new com.orion.adapter.avro.AParticipant();
          }
          this.participant.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










